name: simple_architecture
description: "A new Flutter simple architecture."
publish_to: 'akinayhan'
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.2
  provider: ^6.1.2
  jwt_decoder: ^2.0.1
  http: ^1.3.0
  flutter_localization: ^0.3.1
  intl: ^0.19.0
  ionicons: ^0.2.2
  flutter_launcher_icons: ^0.14.3
  dropdown_button2: ^2.3.9
  url_launcher: ^6.3.1
  excel: ^4.0.6
  share_plus: ^10.1.4
  path_provider: ^2.1.5
  pdf: ^3.11.3
  printing: ^5.14.2
  data_table_2: ^2.5.18
  flutter_downloader: ^1.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/

  fonts:
    - family: OpenSans-Regular
      fonts:
        - asset: assets/Fonts/OpenSans-Regular.ttf
          weight: 700
